# vytdev's starship prompt setup.
# It's not that much, but it's blazingly fast!!
#

"$schema" = 'https://starship.rs/config-schema.json'

# Here's what I actually need:
#
# - username & host
# - curr work dir
# - last err code
# - curr branch
# - date and time
# - how long the last cmd took (optional)
# - "$" or "#" in a new line (optional)

add_newline = true
palette = 'cust'

format = """
[╭](fg:col_grey)\
$directory\
$git_branch\
$fill\
$cmd_duration\
$status\
$time\
$username\
$hostname\
[─](fg:col_grey)\
$line_break\
[╰─](fg:col_grey)\
$character
"""

[palettes.cust]
col_grey =      '#373737'
col_user =      '#e43b16'
col_host =      '#82c826'
col_dir =       '#1580ea'
col_branch =    '#33cc80'
col_time =      '#e37e54'
col_dur =       '#e354aa'
col_stat =      '#e3bd54'

col_green =     '#44ff44'
col_red =       '#ff4242'

[character]
success_symbol = "[ ](bold fg:col_green)"
error_symbol = "[ ](bold fg:col_red)"

[line_break]
disabled = false

[fill]
symbol = '─'
style = 'fg:col_grey'

[username]
format = """[─](fg:col_grey)\
[  ](bg:col_user)[](fg:col_user bg:col_grey)\
[ $user](fg:col_user bg:col_grey)"""
show_always = true

[hostname]
format = """[─](fg:col_grey)\
[  ](bg:col_host)[](fg:col_host bg:col_grey)\
[ $hostname](fg:col_host bg:col_grey)"""
ssh_only = true

[directory]
format = """[─](fg:col_grey)\
[  ](bg:col_dir)[](fg:col_dir bg:col_grey)\
[ $path[$read_only](fg:col_red)](fg:col_dir bg:col_grey)"""
read_only = '  '
truncate_to_repo = true
truncation_length = 2
truncation_symbol = '…/'

[git_branch]
format = """[─](fg:col_grey)\
[  ](bg:col_branch)[](fg:col_branch bg:col_grey)\
[ $branch(:$remote_branch)](fg:col_branch bg:col_grey)"""

[time]
format = """[─](fg:col_grey)\
[  ](bg:col_time)[](fg:col_time bg:col_grey)\
[ $time](fg:col_time bg:col_grey)"""
time_format = '%Y-%m-%d %H:%M'
disabled = false

[cmd_duration]
format = """[─](fg:col_grey)\
[  ](bg:col_dur)[](fg:col_dur bg:col_grey)\
[ $duration](fg:col_dur bg:col_grey)"""
min_time = 1_000

[status]
format = """[─](fg:col_grey)\
[ $symbol ](bg:col_stat)[](fg:col_stat bg:col_grey)\
[ $status](fg:col_stat bg:col_grey)"""
disabled = false
map_symbol = true
symbol = ''
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
signal_symbol = ''
