return {
  'Hello, world!!',
  'Vim\'s a legend.',
  '// TODO: make *chocolate*',
  ':wq -- and off you go',
  'The sacred tool of wisdom.',
  'Vim is not a cult... probably',
  ':term, :term, :term!!',
  'Use fzf.',
  'Tip: Use `<Leader>ff` to fuzzy find files.',
  'Tip: Use `<Leader>fg` to search on your cwd.',
  'Tip: Use `<Leader>fr` to list recent files.',
  'Fancy a project tree? Use `<Leader>e`.',
  '`<Leader>a`: Show the symbols!',
  'Use `gd` to jump to definition.',
  'Press `zz` to center the cursor vertically.',
}
